import { useState, useEffect } from 'react';
import { Target, Plus, Sparkles, CheckSquare, Calendar, Trash2, X } from 'lucide-react';
import { goals as apiGoals } from '../../services/api.js';
import CustomDatePicker from '../Shared/CustomDatePicker.jsx';

export default function GoalsPage() {
  const [goals, setGoals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState(null);

  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('Personal');
  const [targetDate, setTargetDate] = useState(() => new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10));
  const [autoPlan, setAutoPlan] = useState(false);
  const [userPreferences, setUserPreferences] = useState('');
  const [manualMilestones, setManualMilestones] = useState([
    { week: 1, text: '', effort: 'medium' }
  ]);

  const addWeek = () => {
    setManualMilestones(prev => {
      const newLen = prev.length + 1;
      setTargetDate(new Date(Date.now() + newLen * 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10));
      return [
        ...prev,
        { week: newLen, text: '', effort: 'medium' }
      ];
    });
  };

  const removeWeek = (index) => {
    setManualMilestones(prev => {
      const updated = [...prev];
      updated.splice(index, 1);
      const newLen = updated.length;
      setTargetDate(new Date(Date.now() + newLen * 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10));
      return updated.map((m, i) => ({ ...m, week: i + 1 }));
    });
  };

  const updateWeek = (index, field, value) => {
    setManualMilestones(prev => {
      const updated = [...prev];
      updated[index] = { ...updated[index], [field]: value };
      return updated;
    });
  };



  const showToast = (message, type = 'success') => {
    setToast({ message, type });
    setTimeout(() => {
      setToast(null);
    }, 3500);
  };

  const fetchGoals = async () => {
    try {
      setLoading(true);
      const data = await apiGoals.getAll();
      setGoals(data || []);
    } catch (err) {
      console.error('Error fetching goals:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const load = async () => {
      await fetchGoals();
    };
    load();
  }, []);

  const handleAddGoal = async (e) => {
    e.preventDefault();
    if (!title.trim()) return;

    try {
      const created = await apiGoals.create({
        title,
        description: `Category: ${category}`,
        targetDate: new Date(targetDate),
        progress: 0,
        autoPlan,
        userPreferences,
        manualMilestones: autoPlan ? [] : manualMilestones
      });
      setGoals(prev => [...prev, created]);
      setTitle('');
      setCategory('Personal');
      setAutoPlan(false);
      setUserPreferences('');
      setManualMilestones([
        { week: 1, text: '', effort: 'medium' }
      ]);

      if (autoPlan) {
        showToast(`Goal initialized! Milestones are being generated by Gemini...`);

        // Poll goals in 4.5 seconds to get the generated milestones from backend
        setTimeout(async () => {
          const refetched = await apiGoals.getAll();
          setGoals(refetched || []);
        }, 4500);
      } else {
        showToast(`Goal created successfully!`);
      }

    } catch {
      showToast('Error creating goal', 'error');
    }
  };

  const toggleMilestone = async (goalId, milestoneId) => {
    const goal = goals.find(g => g._id === goalId);
    if (!goal) return;

    const updatedMilestones = goal.milestones.map(m => 
      m._id === milestoneId ? { ...m, done: !m.done } : m
    );

    const doneCount = updatedMilestones.filter(m => m.done).length;
    const computedProgress = updatedMilestones.length > 0 
      ? Math.round((doneCount / updatedMilestones.length) * 100) 
      : 0;

    try {
      const updated = await apiGoals.update(goalId, {
        milestones: updatedMilestones,
        progress: computedProgress
      });
      setGoals(prev => prev.map(g => g._id === goalId ? updated : g));
      showToast('Milestone status updated!');
    } catch {
      showToast('Error updating milestone', 'error');
    }
  };

  const handleDeleteGoal = async (id) => {
    try {
      await apiGoals.delete(id);
      setGoals(prev => prev.filter(g => g._id !== id));
      showToast('Goal removed');
    } catch {
      showToast('Error removing goal', 'error');
    }
  };

  return (
    <div className="space-y-5 lg:space-y-8 animate-fade-in font-sans relative">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/5 pb-5">
        <div>
          <span className="text-xs lg:text-sm font-tech font-bold tracking-[0.3em] text-[#E5B842] block mb-1.5 lg:mb-2">TARGET MODULES</span>
          <h2 className="text-2xl lg:text-3xl font-display font-black tracking-tight text-white leading-none">
            Strategic Goals &amp; Milestones
          </h2>
        </div>
      </div>

      {/* Add Goal Panel */}
      <form onSubmit={handleAddGoal} className="p-6 bg-[#090909] border border-white/[0.04] rounded-2xl space-y-4 layered-shadow-lg">
        <h3 className="text-sm font-bold text-[#E5B842] tracking-widest uppercase font-display mb-4">Launch Strategic Target</h3>
        
        <div className="flex flex-col lg:flex-row gap-4 items-center w-full">
          <input 
            type="text"
            placeholder="Name your goal (e.g. Master React Native)"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="flex-1 w-full bg-[#0B0B0B] border border-white/10 hover:border-white/20 focus:border-[#E5B842]/40 rounded-xl px-4 py-3 text-sm text-white placeholder-white/30 focus:outline-hidden transition-all duration-300"
            required
          />

          <div className="flex flex-col sm:flex-row items-center gap-3 w-full lg:w-auto">
            <input 
              type="text"
              placeholder="Category (e.g. Health)"
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full sm:w-[150px] shrink-0 bg-[#0B0B0B] border border-white/10 hover:border-white/20 focus:border-[#E5B842]/40 rounded-xl px-4 py-3 text-sm text-white placeholder-white/30 focus:outline-hidden transition-all duration-300"
              required
            />
            
            <div className="w-full sm:w-[160px] shrink-0 relative group">
              <div className="absolute -top-5 left-1 text-sm font-bold text-[#E5B842] uppercase tracking-wider opacity-0 group-hover:opacity-100 transition-opacity">Target Deadline</div>
              <CustomDatePicker 
                value={targetDate}
                onChange={(dateStr) => {
                  setTargetDate(dateStr);
                  const today = new Date();
                  const target = new Date(dateStr);
                  const diffTime = target - today;
                  if (diffTime <= 0) {
                    setManualMilestones(prev => prev.length === 1 ? prev : prev.slice(0, 1));
                    return;
                  }
                  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
                  const targetWeeks = Math.max(1, Math.ceil(diffDays / 7));
                  
                  setManualMilestones(prev => {
                    if (prev.length === targetWeeks) return prev;
                    if (prev.length < targetWeeks) {
                      const newMilestones = [...prev];
                      for (let i = prev.length; i < targetWeeks; i++) {
                         newMilestones.push({ week: i + 1, text: '', effort: 'medium' });
                      }
                      return newMilestones;
                    } else {
                      return prev.slice(0, targetWeeks);
                    }
                  });
                }}
              />
            </div>
          </div>
        </div>

        {/* AI Planning & Preferences Options */}
        <div className="space-y-4 pt-4 border-t border-white/5">
          <div className="animate-fade-in-up space-y-3">
            <label className="text-sm font-tech font-bold uppercase tracking-wider text-[#E5B842] block mb-2 flex items-center gap-1.5">
              <Sparkles className="w-3 h-3" /> Step 2: Define your weekly milestones (AI will polish them)
            </label>
              
              <div className="space-y-3">
                {manualMilestones.map((m, index) => (
                  <div key={index} className="flex gap-3 items-start bg-white/[0.02] border border-white/5 p-3 rounded-xl relative group">
                    <div className="pt-2 text-sm font-bold text-white/70 uppercase w-12 shrink-0">
                      Wk {m.week}
                    </div>
                    
                    <textarea 
                      rows={1}
                      placeholder={`What to do in Week ${m.week}?`}
                      value={m.text}
                      onChange={(e) => {
                        e.target.style.height = 'auto';
                        e.target.style.height = (e.target.scrollHeight) + 'px';
                        updateWeek(index, 'text', e.target.value);
                      }}
                      className="flex-1 bg-[#050505] border border-white/10 focus:border-[#E5B842]/40 rounded-lg px-3 py-2 text-sm text-white placeholder-white/50 focus:outline-hidden resize-none min-h-[40px] overflow-hidden leading-relaxed"
                    />



                    {manualMilestones.length > 1 && (
                      <button 
                        type="button" 
                        onClick={() => removeWeek(index)}
                        className="text-white/50 hover:text-red-400 p-2 opacity-0 group-hover:opacity-100 transition-opacity absolute -right-2 -top-2 bg-[#090909] rounded-full border border-white/10 cursor-pointer"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                ))}
              </div>

              <button 
                type="button" 
                onClick={addWeek}
                className="text-sm text-[#E5B842]/70 hover:text-[#E5B842] uppercase font-bold tracking-wider flex items-center gap-1 transition-colors cursor-pointer"
              >
                <Plus className="w-3 h-3" /> Add another week
              </button>
            </div>
        </div>

        <div className="flex justify-end">
          <button 
            type="submit"
            className="px-6 py-3 bg-transparent text-[#E5B842] border border-[#E5B842]/40 hover:bg-[#E5B842] hover:text-black hover:border-transparent text-sm font-bold uppercase tracking-wider rounded-xl transition-all duration-300 flex items-center gap-1.5 cursor-pointer font-sans active:scale-[0.98]"
          >
            <Plus className="w-4 h-4" /> Create Goal
          </button>
        </div>
      </form>

      {/* Grid of Goal Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {loading ? (
          <div className="space-y-4 animate-pulse col-span-2">
            <div className="h-48 bg-white/5 rounded-3xl"></div>
            <div className="h-48 bg-white/5 rounded-3xl"></div>
          </div>
        ) : (
          goals.map((goal) => {
            const displayCategory = goal.description && goal.description.startsWith('Category: ')
              ? goal.description.substring(10)
              : 'Goal';

            let insightText = `"Gemini has structured a ${goal.milestones?.length || 0}-week plan for you to follow."`;
            if (goal.targetDate) {
              const today = new Date();
              const target = new Date(goal.targetDate);
              const diffTime = target - today;
              const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
              
              if (diffDays < 0) {
                insightText = goal.progress === 100 
                  ? `"Incredible work! You successfully completed this goal."` 
                  : `"This goal is past its target deadline. Let's wrap up the remaining ${100 - goal.progress}% as soon as possible!"`;
              } else {
                const weeksLeft = Math.floor(diffDays / 7);
                const daysLeft = diffDays % 7;
                let timeLeftStr = weeksLeft > 0 ? `${weeksLeft} week${weeksLeft > 1 ? 's' : ''}` : '';
                if (daysLeft > 0) timeLeftStr += (timeLeftStr ? ' and ' : '') + `${daysLeft} day${daysLeft > 1 ? 's' : ''}`;
                if (!timeLeftStr) timeLeftStr = 'less than a day';
                
                if (goal.progress === 100) {
                  insightText = `"Goal Achieved! You finished with ${timeLeftStr} to spare. Great job!"`;
                } else if (goal.progress === 0) {
                  insightText = `"You have ${timeLeftStr} to complete this goal. Gemini has mapped out the steps to get you there."`;
                } else if (diffDays <= 7 && goal.progress < 80) {
                  insightText = `"Crunch time! You have only ${timeLeftStr} left to finish the final ${100 - goal.progress}%. Let's focus!"`;
                } else {
                  insightText = `"You're making steady progress. You have ${timeLeftStr} left to complete the remaining milestones."`;
                }
              }
            }

            return (
              <div key={goal._id} className="p-6 bg-[#090909] border border-white/[0.04] rounded-3xl space-y-6 flex flex-col justify-between layered-shadow-lg">
                <div className="space-y-4">
                  
                  {/* Header card details */}
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <span className="text-sm bg-[#E5B842]/5 border border-[#E5B842]/20 text-[#E5B842] px-2.5 py-0.5 rounded-full font-bold uppercase tracking-wider">
                        {displayCategory}
                      </span>
                      <h3 className="text-sm font-bold text-white mt-2 leading-snug">{goal.title}</h3>
                    </div>
                    
                    {/* SVG Progress Ring */}
                    <div className="relative w-12 h-12 flex items-center justify-center shrink-0">
                      <svg className="w-full h-full transform -rotate-90">
                        <circle cx="24" cy="24" r="20" stroke="rgba(255,255,255,0.05)" strokeWidth="3" fill="transparent" />
                        <circle 
                          cx="24" 
                          cy="24" 
                          r="20" 
                          stroke="#E5B842" 
                          strokeWidth="3" 
                          fill="transparent" 
                          strokeDasharray="125.6" 
                          strokeDashoffset={125.6 - (125.6 * (goal.progress || 0)) / 100}
                        />
                      </svg>
                      <span className="absolute text-sm font-bold text-[#E5B842]">{goal.progress || 0}%</span>
                    </div>
                  </div>

                  {/* Target date indicator */}
                  <div className="flex items-center justify-between text-sm text-white/70 uppercase font-bold">
                    <div className="flex items-center gap-1">
                      <Calendar className="w-3.5 h-3.5 text-[#E5B842]/80" /> Target: {new Date(goal.targetDate).toLocaleDateString()}
                    </div>
                    <button 
                      onClick={() => handleDeleteGoal(goal._id)}
                      className="text-white/50 hover:text-red-500 transition-colors p-1 cursor-pointer"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  {/* Milestones list */}
                  <div className="space-y-2">
                    <h4 className="text-sm uppercase font-bold text-white/60 tracking-widest">Milestones Checklist</h4>
                    {goal.milestones && goal.milestones.length > 0 ? (
                      goal.milestones.map((milestone) => (
                        <div 
                          key={milestone._id}
                          onClick={() => toggleMilestone(goal._id, milestone._id)}
                          className="flex items-center gap-2.5 p-2.5 bg-black/40 border border-white/[0.03] rounded-xl cursor-pointer hover:border-white/10 transition-all duration-300"
                        >
                          {milestone.done ? (
                            <CheckSquare className="w-4 h-4 text-[#E5B842]" fill="rgba(229,184,66,0.1)" />
                          ) : (
                            <div className="w-4 h-4 rounded-sm border border-white/20"></div>
                          )}
                          <span className={`text-[13px] leading-relaxed ${milestone.done ? 'line-through text-white/35' : 'text-white/80'}`}>
                            Week {milestone.week}: {milestone.milestone} <span className="text-sm text-[#E5B842]/80 uppercase tracking-widest ml-1.5 font-bold">({milestone.effort} effort)</span>
                          </span>
                        </div>
                      ))
                    ) : (
                      <p className="text-sm text-white/60 italic">No milestones loaded yet.</p>
                    )}
                  </div>

                </div>

                {/* AI Review Insight */}
                {goal.milestones && goal.milestones.length > 0 && (
                  <div className="p-4 bg-white/[0.01] border border-[#E5B842]/20 rounded-2xl relative overflow-hidden card-shine-sweep mt-4">
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <Sparkles className="w-3.5 h-3.5 text-[#E5B842]" />
                      <span className="text-sm font-bold text-white uppercase tracking-wider font-display">AI Timeline Breakdown</span>
                    </div>
                    <p className="text-sm text-white/80 font-normal leading-relaxed mt-1.5">
                      {insightText}
                    </p>
                  </div>
                )}

              </div>
            );
          })
        )}
      </div>

      {/* Toast Notification */}
      {toast && (
        <div className={`fixed bottom-20 lg:bottom-6 left-4 right-4 sm:left-auto sm:right-6 sm:w-auto z-50 px-4 sm:px-5 py-3 sm:py-3.5 rounded-2xl border backdrop-blur-md shadow-2xl flex items-center gap-3 animate-fade-in ${
          toast.type === 'error' 
            ? 'bg-status-red/10 border-status-red/30 text-status-red' 
            : 'bg-black/90 border-[#E5B842]/30 text-[#E5B842]'
        }`}>
          <Target className="w-4 h-4" />
          <span className="text-sm font-bold tracking-wide uppercase">{toast.message}</span>
        </div>
      )}

    </div>
  );
}
