import React, { useState, useEffect } from 'react';
import { Target, Plus, Sparkles, CheckSquare, Calendar, Trash2 } from 'lucide-react';
import { goals as apiGoals } from '../../services/api.js';
import CustomDatePicker from '../Shared/CustomDatePicker.jsx';

export default function GoalsPage() {
  const [goals, setGoals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState(null);

  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('Personal');
  const [targetDate, setTargetDate] = useState(new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10));
  const [autoPlan, setAutoPlan] = useState(true);
  const [userPreferences, setUserPreferences] = useState('');

  const showToast = (message, type = 'success') => {
    setToast({ message, type });
    setTimeout(() => {
      setToast(null);
    }, 3500);
  };

  const fetchGoals = async () => {
    try {
      setLoading(true);
      const data = await apiGoals.getAll();
      setGoals(data || []);
    } catch (err) {
      console.error('Error fetching goals:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchGoals();
  }, []);

  const handleAddGoal = async (e) => {
    e.preventDefault();
    if (!title.trim()) return;

    try {
      const created = await apiGoals.create({
        title,
        description: `Category: ${category}`,
        targetDate: new Date(targetDate),
        autoPlan,
        userPreferences: autoPlan ? userPreferences : ''
      });
      setGoals(prev => [...prev, created]);
      setTitle('');
      setUserPreferences('');

      if (autoPlan) {
        showToast(`Goal initialized! Milestones are being generated by Gemini...`);

        // Poll goals in 4.5 seconds to get the generated milestones from backend
        setTimeout(async () => {
          const refetched = await apiGoals.getAll();
          setGoals(refetched || []);
        }, 4500);
      } else {
        showToast(`Goal created successfully!`);
      }

    } catch (err) {
      showToast('Error creating goal', 'error');
    }
  };

  const toggleMilestone = async (goalId, milestoneId) => {
    const goal = goals.find(g => g._id === goalId);
    if (!goal) return;

    const updatedMilestones = goal.milestones.map(m => 
      m._id === milestoneId ? { ...m, done: !m.done } : m
    );

    const doneCount = updatedMilestones.filter(m => m.done).length;
    const computedProgress = updatedMilestones.length > 0 
      ? Math.round((doneCount / updatedMilestones.length) * 100) 
      : 0;

    try {
      const updated = await apiGoals.update(goalId, {
        milestones: updatedMilestones,
        progress: computedProgress
      });
      setGoals(prev => prev.map(g => g._id === goalId ? updated : g));
      showToast('Milestone status updated!');
    } catch (err) {
      showToast('Error updating milestone', 'error');
    }
  };

  const handleDeleteGoal = async (id) => {
    try {
      await apiGoals.delete(id);
      setGoals(prev => prev.filter(g => g._id !== id));
      showToast('Goal removed');
    } catch (err) {
      showToast('Error removing goal', 'error');
    }
  };

  return (
    <div className="space-y-8 animate-fade-in font-sans relative">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 border-b border-white/5 pb-6">
        <div>
          <span className="text-xs font-tech font-bold tracking-[0.3em] text-[#E5B842] block mb-2">TARGET MODULES</span>
          <h2 className="text-3xl font-display font-black tracking-tight text-white leading-none">
            Strategic Goals & Milestones
          </h2>
        </div>
      </div>

      {/* Add Goal Panel */}
      <form onSubmit={handleAddGoal} className="p-6 bg-[#090909] border border-white/[0.04] rounded-2xl space-y-4 layered-shadow-lg">
        <h3 className="text-[10px] font-bold text-[#E5B842] tracking-widest uppercase font-display">Launch Strategic Target</h3>
        <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
          <input 
            type="text"
            placeholder="Name your goal (e.g. Master React Native)"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="md:col-span-6 bg-[#0B0B0B] border border-white/10 hover:border-white/20 focus:border-[#E5B842]/40 rounded-xl px-4 py-3 text-xs text-white placeholder-white/30 focus:outline-hidden transition-all duration-300"
            required
          />
          <input 
            type="text"
            placeholder="Category (e.g. Health, Work)"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            className="md:col-span-3 bg-[#0B0B0B] border border-white/10 hover:border-white/20 focus:border-[#E5B842]/40 rounded-xl px-4 py-3 text-xs text-white placeholder-white/30 focus:outline-hidden transition-all duration-300"
            required
          />
          <CustomDatePicker 
            value={targetDate}
            onChange={(dateStr) => setTargetDate(dateStr)}
          />
        </div>

        {/* AI Planning & Preferences Options */}
        <div className="space-y-3 pt-2 border-t border-white/5">
          <label className="flex items-center gap-2.5 cursor-pointer text-xs text-white/70 hover:text-white transition-colors">
            <input 
              type="checkbox" 
              checked={autoPlan} 
              onChange={e => setAutoPlan(e.target.checked)}
              className="w-4 h-4 rounded border-white/10 text-[#E5B842] focus:ring-0 focus:ring-offset-0 bg-black cursor-pointer"
            />
            <span className="font-semibold uppercase tracking-wider text-[10px] text-white/65">
              Plan milestones automatically with Gemini AI
            </span>
          </label>

          {autoPlan && (
            <div className="animate-fade-in-up">
              <label className="text-[9px] font-tech font-bold uppercase tracking-wider text-white/40 block mb-1.5">Focus Areas & Preferences (Optional)</label>
              <textarea 
                placeholder="e.g. Focus on basics first, I can allocate 5 hours a week, I have some prior JavaScript knowledge"
                value={userPreferences}
                onChange={(e) => setUserPreferences(e.target.value)}
                className="w-full bg-[#0B0B0B] border border-white/10 hover:border-white/20 focus:border-[#E5B842]/45 rounded-xl px-4 py-2.5 text-xs text-white placeholder-white/20 focus:outline-hidden transition-all duration-300 h-16 resize-none"
              />
            </div>
          )}
        </div>

        <div className="flex justify-end">
          <button 
            type="submit"
            className="px-6 py-3 bg-transparent text-[#E5B842] border border-[#E5B842]/40 hover:bg-[#E5B842] hover:text-black hover:border-transparent text-xs font-bold uppercase tracking-wider rounded-xl transition-all duration-300 flex items-center gap-1.5 cursor-pointer font-sans active:scale-[0.98]"
          >
            <Plus className="w-4 h-4" /> Create Goal
          </button>
        </div>
      </form>

      {/* Grid of Goal Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {loading ? (
          <div className="space-y-4 animate-pulse col-span-2">
            <div className="h-48 bg-white/5 rounded-3xl"></div>
            <div className="h-48 bg-white/5 rounded-3xl"></div>
          </div>
        ) : (
          goals.map((goal) => {
            const displayCategory = goal.description && goal.description.startsWith('Category: ')
              ? goal.description.substring(10)
              : 'Goal';

            return (
              <div key={goal._id} className="p-6 bg-[#090909] border border-white/[0.04] rounded-3xl space-y-6 flex flex-col justify-between layered-shadow-lg">
                <div className="space-y-4">
                  
                  {/* Header card details */}
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <span className="text-[10px] bg-[#E5B842]/5 border border-[#E5B842]/20 text-[#E5B842] px-2.5 py-0.5 rounded-full font-bold uppercase tracking-wider">
                        {displayCategory}
                      </span>
                      <h3 className="text-sm font-bold text-white mt-2 leading-snug">{goal.title}</h3>
                    </div>
                    
                    {/* SVG Progress Ring */}
                    <div className="relative w-12 h-12 flex items-center justify-center shrink-0">
                      <svg className="w-full h-full transform -rotate-90">
                        <circle cx="24" cy="24" r="20" stroke="rgba(255,255,255,0.05)" strokeWidth="3" fill="transparent" />
                        <circle 
                          cx="24" 
                          cy="24" 
                          r="20" 
                          stroke="#E5B842" 
                          strokeWidth="3" 
                          fill="transparent" 
                          strokeDasharray="125.6" 
                          strokeDashoffset={125.6 - (125.6 * (goal.progress || 0)) / 100}
                        />
                      </svg>
                      <span className="absolute text-[9px] font-bold text-[#E5B842]">{goal.progress || 0}%</span>
                    </div>
                  </div>

                  {/* Target date indicator */}
                  <div className="flex items-center justify-between text-[10px] text-white/40 uppercase font-bold">
                    <div className="flex items-center gap-1">
                      <Calendar className="w-3.5 h-3.5 text-[#E5B842]/80" /> Target: {new Date(goal.targetDate).toLocaleDateString()}
                    </div>
                    <button 
                      onClick={() => handleDeleteGoal(goal._id)}
                      className="text-white/20 hover:text-red-500 transition-colors p-1 cursor-pointer"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  {/* Milestones list */}
                  <div className="space-y-2">
                    <h4 className="text-[10px] uppercase font-bold text-white/30 tracking-widest">Milestones Checklist</h4>
                    {goal.milestones && goal.milestones.length > 0 ? (
                      goal.milestones.map((milestone) => (
                        <div 
                          key={milestone._id}
                          onClick={() => toggleMilestone(goal._id, milestone._id)}
                          className="flex items-center gap-2.5 p-2.5 bg-black/40 border border-white/[0.03] rounded-xl cursor-pointer hover:border-white/10 transition-all duration-300"
                        >
                          {milestone.done ? (
                            <CheckSquare className="w-4 h-4 text-[#E5B842]" fill="rgba(229,184,66,0.1)" />
                          ) : (
                            <div className="w-4 h-4 rounded-sm border border-white/20"></div>
                          )}
                          <span className={`text-xs ${milestone.done ? 'line-through text-white/35' : 'text-white/70'}`}>
                            Week {milestone.week}: {milestone.milestone} <span className="text-[8px] text-[#E5B842]/70 uppercase tracking-widest ml-1 font-bold">({milestone.effort} effort)</span>
                          </span>
                        </div>
                      ))
                    ) : (
                      <p className="text-[10px] text-white/30 italic">No milestones loaded yet.</p>
                    )}
                  </div>

                </div>

                {/* AI Review Insight */}
                {goal.milestones && goal.milestones.length > 0 && (
                  <div className="p-4 bg-white/[0.01] border border-[#E5B842]/20 rounded-2xl relative overflow-hidden card-shine-sweep mt-4">
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <Sparkles className="w-3.5 h-3.5 text-[#E5B842]" />
                      <span className="text-[9px] font-bold text-white uppercase tracking-wider font-display">AI Timeline Breakdown</span>
                    </div>
                    <p className="text-[11px] text-white/70 font-light leading-relaxed">
                      "Gemini completed target analysis and established a {goal.milestones.length}-week milestone path mapping low/medium/high effort levels."
                    </p>
                  </div>
                )}

              </div>
            );
          })
        )}
      </div>

      {/* Toast Notification */}
      {toast && (
        <div className={`fixed bottom-6 right-6 z-50 px-5 py-3.5 rounded-2xl border backdrop-blur-md shadow-2xl flex items-center gap-3 animate-fade-in ${
          toast.type === 'error' 
            ? 'bg-status-red/10 border-status-red/30 text-status-red' 
            : 'bg-black/90 border-[#E5B842]/30 text-[#E5B842]'
        }`}>
          <Target className="w-4 h-4" />
          <span className="text-xs font-bold tracking-wide uppercase">{toast.message}</span>
        </div>
      )}

    </div>
  );
}
